name: Check Perl files

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  compilation-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install perl packages
        run: ./deploy/packages.sh
      
      - name: Check Perl files
        run: ./deploy/run_checks.sh

